import {
  BTCLogo,
  CNLogo,
  ETHLogo,
  JSTLogo,
  NFTLogo,
  OSKLogo,
  POSCHELogo,
  SafeMoneyLogo,
  SUNLogo,
  TRXLogo,
  TUSDLogo,
  USDCLogo,
  USDJLogo,
  WBTTLogo,
  WINLogo,
} from '../assets/icons/tokens';
import { TypeToken } from '../types';

import { isProduction } from './index';

export const tokenList: TypeToken[] = isProduction
  ? [
      {
        name: 'TRX',
        symbol: 'TRX',
        address: '',
        decimals: 6,
        logo: TRXLogo,
      },
      {
        name: 'SafeMoney',
        symbol: 'SMT',
        address: 'TNBrVEzuVYbNbGF2ua3ivSX5Y5V9N4xhax',
        decimals: 8,
        logo: SafeMoneyLogo,
      },
      {
        name: 'OSK',
        symbol: 'OSK',
        address: 'TDk91SWz2GvwfZwMTGX21d4ngUUH8YZZAv',
        decimals: 18,
        logo: OSKLogo,
      },
      {
        name: 'Wrapped BitTorrent',
        symbol: 'WBTT',
        address: 'TKfjV9RNKJJCqPvBtK8L7Knykh7DNWvnYt',
        decimals: 6,
        logo: WBTTLogo,
      },
      {
        name: 'JUST GOV v1.0',
        symbol: 'JST',
        address: 'TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9',
        decimals: 18,
        logo: JSTLogo,
      },
      {
        name: 'Bitcoin',
        symbol: 'BTC',
        address: 'TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9',
        decimals: 8,
        logo: BTCLogo,
      },
      {
        name: 'JUST Stablecoin v1.0',
        symbol: 'USDJ',
        address: 'TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT',
        decimals: 18,
        logo: USDJLogo,
      },
    {
        name: 'testoken',
        symbol: 'test',
        address: 'TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8',
        decimals: 6,
        logo: TRXlogo,
      },
      {
        name: 'SUN TOKEN',
        symbol: 'SUN',
        address: 'TSSMHYeV2uE9qYH95DqyoCuNCzEL1NvU3S',
        decimals: 18,
        logo: SUNLogo,
      },
      {
        name: 'WINK',
        symbol: 'WIN',
        address: 'TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7',
        decimals: 6,
        logo: WINLogo,
      },
      {
        name: 'TrueUSD',
        symbol: 'TUSD',
        address: 'TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4',
        decimals: 18,
        logo: TUSDLogo,
      },
      {
        name: 'APENFT',
        symbol: 'NFT',
        address: 'TFczxzPhnThNSqr5by8tvxsdCFRRz6cPNq',
        decimals: 6,
        logo: NFTLogo,
      },
      {
        name: 'USD Coin',
        symbol: 'USDC',
        address: 'TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8',
        decimals: 6,
        logo: USDCLogo,
      },
      {
        name: 'Ethereum',
        symbol: 'ETH',
        address: 'THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF',
        decimals: 18,
        logo: ETHLogo,
      },
      {
        name: 'POSCHE Token',
        symbol: 'POSCHE',
        address: 'TYofwf9oM6CPU1rCTwNnEuwzhB5DTQu8rW',
        decimals: 6,
        logo: POSCHELogo,
      },
      {
        name: 'BreedTech',
        symbol: 'CN',
        address: 'TGTE9Eo4hrkotStM1iGHSKA7gobxZxPuwQ',
        decimals: 6,
        logo: CNLogo,
      },
    ]
  : [
      {
        name: 'TRX',
        symbol: 'TRX',
        address: '',
        decimals: 6,
        logo: TRXLogo,
      },
      {
        name: 'Solana',
        symbol: 'SOL',
        address: 'TMCtbHNYWavDHBPEcJvDij6uAUU3cHq5xJ',
        decimals: 18,
        logo: TRXLogo,
      },
      {
        name: 'Cardano',
        symbol: 'ADA',
        address: 'TSk6XgRK6k9Y9nwcLx3ZJXf4XA9eurtceK',
        decimals: 18,
        logo: TRXLogo,
      },
      {
        name: 'DOGE',
        symbol: 'DOGE',
        address: 'TDNSKtL8vSWeGPFGm9TymtJptqNcotBWHG',
        decimals: 18,
        logo: TRXLogo,
      },
    ];
